version: "3"
services:
  hub:
    image: selenium/hub:3.14
#  don't need port mapping
#    ports:
#      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on: 
      - hub 
    environment: 
      - HUB_HOST=hub 
  search-module:
    image: ransomeli/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result1:/usr/share/udemy/test-output
  search-module2:
    image: ransomeli/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./search-result2:/usr/share/udemy/test-output    
  book-flight-module1:
    image: ransomeli/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=book-flight-module.xml
    volumes:
      - ./book-result1:/usr/share/udemy/test-output
   
